# Generated by Django 4.0.5 on 2022-06-25 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_category_alter_listing_latest_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latest_bid',
        ),
    ]
